# kustumization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: store-app
resources:
  - mongodb.yaml
  - rabbitmq.yaml
  - order-service.yaml
  - makeline-service.yaml
  - product-service.yaml
  - store-front.yaml
  - product-service-grpc.yaml
  - store-front-grpc.yaml
  - store-admin.yaml
  - virtual-costumer.yaml
  - virtual-worker.yaml
  - service-monitor.yaml

namespace: store-app