# kustumization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: store-app
resources:
  - deployment.yaml  

namePrefix: store-
nameSuffix: -v1
namespace: store-app