apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor
  metadata: 
    name: service-monitor-service 
    labels: 
      app: service-monitor-service 
spec: 
  selector: 
    matchLabels: 
      app: product-service-grpc
  endpoints: 
  - interval: 30s
    port: web